//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURES_FOURNISSEURS
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int FOURNISSEUR { get; set; }
        public Nullable<int> Societes { get; set; }
        public Nullable<decimal> THT { get; set; }
        public Nullable<decimal> TTVA { get; set; }
        public Nullable<decimal> NHT { get; set; }
        public decimal TTC { get; set; }
        public Nullable<decimal> TNET { get; set; }
        public bool VALIDER { get; set; }
        public bool PAYEE { get; set; }
        public Nullable<int> COMMANDE_FOURNISSEUR { get; set; }
        public Nullable<int> BON_RECEPTION_FOURNISSEUR { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public Nullable<decimal> TIMBRE { get; set; }
        public Nullable<int> Tiers { get; set; }
        public Nullable<decimal> FODEC { get; set; }
        public Nullable<decimal> Redevance { get; set; }
        public string Num_Fact { get; set; }
        public Nullable<bool> Declaration { get; set; }
        public Nullable<System.DateTime> Date_Declaration { get; set; }
        public Nullable<bool> immobilisation { get; set; }
        public Nullable<bool> Bien_service { get; set; }
        public Nullable<bool> RAS_Marche { get; set; }
        public string MOIS_RAS_Marche { get; set; }
        public Nullable<int> ID_RETENUE { get; set; }
    }
}
