//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trEntities1 : DbContext
    {
        public trEntities1()
            : base("name=trEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Art_Depot_Rayon> Art_Depot_Rayon { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<Dépot> Dépot { get; set; }
        public virtual DbSet<Devise> Devise { get; set; }
        public virtual DbSet<Exercice> Exercice { get; set; }
        public virtual DbSet<FACTURES_CLIENTS> FACTURES_CLIENTS { get; set; }
        public virtual DbSet<FACTURES_FOURNISSEURS> FACTURES_FOURNISSEURS { get; set; }
        public virtual DbSet<FOURNISSEURS> FOURNISSEURS { get; set; }
        public virtual DbSet<Marque> Marque { get; set; }
        public virtual DbSet<mouvement> mouvement { get; set; }
        public virtual DbSet<Prix_Achat> Prix_Achat { get; set; }
        public virtual DbSet<Rayons> Rayons { get; set; }
        public virtual DbSet<Sous_Categorie> Sous_Categorie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TVA> TVA { get; set; }
        public virtual DbSet<Unite> Unite { get; set; }
    }
}
