//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prix_Achat
    {
        public int Product_ID { get; set; }
        public string Designation { get; set; }
        public string Marque { get; set; }
        public Nullable<int> Categorie { get; set; }
        public Nullable<int> Sous_Categorie { get; set; }
        public string Unite { get; set; }
        public Nullable<double> PU_HT_Sans_Remise { get; set; }
        public Nullable<int> Remise { get; set; }
        public Nullable<double> PU_HT_Avec_Remise { get; set; }
        public string Devise { get; set; }
        public string Valeur_TVA { get; set; }
        public Nullable<double> PU_TTC { get; set; }
        public Nullable<int> Fournisseur { get; set; }
        public Nullable<System.DateTime> Date_offre_de_prix { get; set; }
        public Nullable<int> Duree_de_validite { get; set; }
        public string N_Offre_de_Prix { get; set; }
        public Nullable<double> QUANTITE { get; set; }
        public Nullable<int> QUANTITE_REPTURE_STOCK { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> BLfRS { get; set; }
        public Nullable<double> Stock { get; set; }
        public Nullable<double> Stock_Alerte { get; set; }
    
        public virtual FOURNISSEURS FOURNISSEURS { get; set; }
    }
}
