//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sous_Categorie
    {
        public int CatID { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> CentreID { get; set; }
    
        public virtual Categorie Categorie { get; set; }
    }
}
